Hello, traveler. This is the beginning of a log file called: "Fascist Tweet Archiver".
Some basic system info about the host machine: posix.uname_result(sysname='Linux', nodename='linawesome', release='4.9.0-4-amd64', version='#1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)', machine='x86_64')
This log was begun Monday, 08 January 2018 at 15:51



INFO: read target account data; we're tracking 52 accounts
WARNING: no ProtocolError (got exception "name 'ProtocolError' is not defined");
 trying requests.packages.urllib3.exceptions instead
NOTE: successfully imported from requests
Starting up...
